source 'https://rubygems.org'

gem 'jquery-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'sqlite3'
gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'simple_form', '3.1.0.rc2'
gem 'uglifier'
gem 'unicorn'
gem 'blacklight'
gem 'sunspot_rails'
gem 'sunspot_solr'
gem 'tinymce-rails', '4.0.11'
gem 'blacklight-maps'
group :development do
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'capistrano', '~> 2.0'
end
group :development, :test do
  gem 'awesome_print'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 2.14.0'
  gem 'coveralls', :require => false
  gem 'simplecov'
  gem 'capybara-screenshot'
end
gem "jettywrapper", "~> 1.7"
gem "devise"
gem "devise-guests", "~> 0.3"

gem "rsolr", "~> 1.0.11"
