# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a4c04c4f984508998a684569adfc49abdbae99c795b4e0a4506814ebaff64c8049cc8d85406cdf0f09ec8d97813bed239a865db0d83d4a873f6498c2e1494d2

test:
  secret_key_base: fc39d8cc867885db65458a867561906d291f65b7e051aeca06dbd5d873067709ab23444acfa060e041058674eb3a30f8ab5e6db103412a65e7ee643b536f1c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
